### PR TITLE
Step-geometry

### PR DESCRIPTION
**Pull request by constantinius**
Fixing rounding errors when calculating dimension step size
Fixing calculating geometry, by adjusting for "pixel is area"

### CODE REVIEW

**Review by gadomski — COMMENTED** [review]
Looks like this includes the diff from https://github.com/stactools-packages/datacube/pull/10, so I'm going to mark this as draft until that one's merged.

**Review by gadomski — COMMENTED** [review]
Is there any simple test case we can add for this one? I _think_ I understand what's going on, but a test could help future me/someone know what the expected behavior should be.

**Comment by constantinius** [comment]
I will try to come up with some tests

**Review by gadomski — APPROVED** [review]

**Comment by gadomski** [comment]
LGTM but needs lints fixed.

**Pull request merged**
